### ISSUE TITLE
Channel created with 'create' as id when calling create() method

### ISSUE THREAD

**Issue by PaulJNewell** [l3nz/ari4java#116]
Calling the create() method on an ActionChannels object, creates (and calls) a channel with an id of 'create' rather than the specified id; which means this method can only be called once because all subsequent attempts will result in a duplicate id error. This occurs because the root of the url is specified as /channels/create which doesn't seem to conform to the API definition; i.e. there is no 'create' verb and so instead this is interpreted as the channel id. I assume this is a bug, unless I am missing something.

**Comment by NaamaGertel** [comment]
Hi @PaulJNewell ,
I'm not sure I completely understood you, but `create()` method is available since Asterisk 14 according to the asterisk documentation and is available since ari 1_10_0 version and the method gets all needed arguments (https://wiki.asterisk.org/wiki/display/AST/Asterisk+14+Channels+REST+API#Asterisk14ChannelsRESTAPI-create). If you specify the same channel id more then once it make sens you get the duplicate id as you mentioned, and that's because it must be unique. 
As far as I know, if you want to create a channel and dial immediately you need to use `originate()` method (be aware that there are originate methods in ari4java that are unsupported, so make sure you are using one that is supported), but if you want to create a channel using `create()` you will need to use the `dial()` method as well. 
If I misunderstood you please extend more your case. hope this helps :)
