### ISSUE TITLE
Throws exception on successful (201) HTTP response code

### ISSUE THREAD

**Issue by korvus81** [l3nz/ari4java#33]
I'm using ARI 1.8.0 on Asterisk 13.5.0 and I noticed I was getting an exception thrown every time I tried to play an audio file, but the play was successful.  When I ngrep'd the traffic, I saw this was the response:

```
HTTP/1.1 201 Created
Server: Asterisk/13.5.0
Date: Wed, 23 Sep 2015 17:49:51 GMT
Connection: close
Cache-Control: no-cache, no-store
Location: /playback/3kH7iFgvjn
Content-type: application/json
Content-Length: 144

{
  "id": "3kH7iFgvjn",
  "media_uri": "sound:tt-weasels",
  "target_uri": "channel:1443030590.10",
  "language": "en-us",
  "state": "queued"
}
```

In ```classes/ch/loway/oss/ari4java/tools/http/NettyHttpClient.java```, the code explicitly checks for OK (200) and NO_CONTENT (204), but a 201 will fall through to the exception throwing code.  I assume this is new behavior on behalf of Asterisk, but a 201 should still be considered successful.

**Comment by l3nz** [comment]
I see that in the Swagger definition there are listed only 4XX error codes, and not 2XX codes. 
I would then whitelist all 2XX codes, because I guess they are not defined and may change at any point in time.
I saw your patch, and if you don't mind, please edit it so that we have a boolean method isSuccess(httpCode), and then in the method at the moment we let all known 2XX codes through. This way if we ever have to change this in the future, we can edit only one point.

PS: Thanks for contribuiting!

**Comment by michaelpetruzzellocivicom** [comment]
I've noticed this with other commands as well. This is something I'll be working on in the future, unless I'm beaten to it.

**Comment by l3nz** [comment]
It is quite simple but would appreciate patches :)

**Comment by korvus81** [comment]
Ok, does my updated PR match what you want?  I can't get my IDE to understand the project nor Gradle to build it without tweaks, and I don't feel like fighting it, so you might want to double-check for typos...

**Comment by l3nz** [comment]
Looks good! I'll edit the function a bit to use consistent bracing of the return value, but really - much appreciated!

**Comment by l3nz** [comment]
New version released.
