### ISSUE TITLE
Rebuild for ARI 2.0.0 (Asterisk 14.2)

### ISSUE THREAD

**Issue by l3nz** [l3nz/ari4java#62]
See https://code.asterisk.org/code/changelog/asterisk?cs=7af1aae57f5d4b1debc1fa18b34fb1a33b0f9965

See issue #61

**Comment by drenda** [comment]
Hi, is the library still alive? Thanks

**Comment by l3nz** [comment]
Shouldn't it?

**Comment by drenda** [comment]
Hi, I was wondering if it still usable because last commit was several months ago and I did not know if it is compatible with last release of Asterisk (14.2.1) just because in the preface text you speak only of Asterisk 12/13.

Another question if I'm not too boring: is the connection with ARI reliable enough over Internet? I played a bit with websockets for some applications and I saw that there are many issue with autoreconnect and problems due to the network in the middle. This could bring to lose events, and do that while you are mananing a call that is arriving or that you are making could be a problem.

Do you have some feedbacks to give me on this side? Thanks a lot

**Comment by modrljin** [comment]
Hi,

 

You’ll have a problems with Asterisk 14. Check this out https://github.com/l3nz/ari4java/pull/61

 

I made it in my fork, Lenz is planning to do this, at least he said so.

 

Best regards,

Marin

**Comment by l3nz** [comment]
ARI 2.0.0 supported.
