### ISSUE TITLE
Supporting Go-ari-proxy

### ISSUE THREAD

**Issue by l3nz** [l3nz/ari4java#82]
It would be interesting to be able to support go-ari-proxy - https://github.com/nvisibleinc/go-ari-proxy - as it seems to be more or less the standard choice for Asterisk ARI clusters.

Ideally I would love to have a GoAriNatsClient / GoAriRabbitClient that replaces the NettyClient like:

	ARI ari = new ARI();
	GoAriClient ac = new GoAriNatsClient();
	ac.initialize("server", "user", "pass");
	ari.setHttpClient(ac);
	ari.setWsClient(ac);
	ari.setVersion(AriVersion.ARI_2_0_0);

And no other changes, so that you basically swap out the connection and it just works.

Maybe we could also have something like:

       ARI ari = ARI.connectTo( "gap-nats://1.2.3.4:8888", user, pass, AriVersion.ARI_2_0_0);

That wraps clients automatically based on the connection URI.

What do you think?

**Comment by bentito** [comment]
Yes, that sounds like a good way to go. I'll head in that direction today and let you know if I see any difficulties.

**Comment by bentito** [comment]
So you don't really mean replace full NettyClient? ari4java would still use Netty as-is for connections to a single Asterisk as originally built, right? Additionally, we would add support for a NATS/RABBITMQ based connection. Perhaps overloading `setHttpClient` and `setWsClient` such that if they are are passed a rabbitmq or NATS client they will use them for app layer transport instead of http? I am suggesting overloading to allow current code using ari4java to not break.

**Comment by l3nz** [comment]
Both `HttpClient` and `WsClient` are interfaces, so anything that supports them can (should) be used plug-and-play along existing NettyClient. A4J only uses those interfaces and is not aware of the details of what goes on within each client.

**Comment by l3nz** [comment]
My question today is: how do you tell which ARI system you are targeting? do you use different topics for different Asterisk boxes?

**Comment by grahambrown11** [comment]
Closing as go-ari-proxy has been abandoned and started a new issue on implementing such within this library
