### ISSUE TITLE
Websockets should not reconnect automatically

### ISSUE THREAD

**Issue by rattenburg** [l3nz/ari4java#85]
Because:
1) The user does not get informed that he might have **missed important events**!
2) There is a bug (current release 0.4.5) with an **infinite reconnect loop** when connecting to a port that does not answer properly (ie. that accepts the TCP connection but does not send anything).

In my opinion, a clean solution would close the connection if something went wrong up to the level of the websocket protocol (including websocket ping; excluding JSON errors on a received text frame).
The user should then receive `onFailure(..)` via the `AriCallback` and can decide on his own what's the best way to deal with this situation.

**Comment by rattenburg** [comment]
To remove automatic reconnecting, you can merge my commit:
https://github.com/rattenburg/ari4java/tree/feature_no_reconnect

**Comment by grahambrown11** [comment]
Hi @rattenburg, rather then completely removing a feature why not add the callback events so the calling program can be aware of the reconnect attempts and if you really want to be in control the auto reconnect add a flag to disable it...

I've been using this code in production for over a year with no problems.

I understand that events can be missed when not connected to Asterisk but unfortunately Asterisk does not queue and keep them so it's difficult to recover from missed events.
I have a background cleanup job that loops through my state objects and checks for inconsistencies (ie no event in the last hour) then assume I've missed an event and the call is abandoned and clean up.

I'm not sure I understand the infinite reconnect loop, there is a check for 10 reconnect attempts if there are more then 10 then `onFailure()` is called and does not reconnect. I dont think it's worth trying to fix an issue due to incorrect configuration to a TCP port that is not a web socket, that should only happen once at startup and once the issue is resolved it should never happen again...

**Comment by l3nz** [comment]
I am with @grahambrown11 on this issue - it would make sense to produce events like "UnexpectedDisconnection" and "AttemptingReconnect" and "Reconnected" so you know that you missed something and the state you're holding on your server might be out of sync, but I for one do not want to handle ARI events as something I need to manage - they should "just happen".  

In any case, having programmed on/in Asterisk for like 15 years now, I have learnt to be quite defensive in programming even while everything appears to be okay... :-)

**Comment by rattenburg** [comment]
Our application reacts on incomming channels by creating/ringing other channels, updating states and bridging them if someone picked up the phone.
This is why we have to know when the event stream broke down in order to clean up the orphaned channels and bridges that have been created.

What do you think about an additional parameter or an addition method to create a websocket connection without automatic reconnection?

One last question:
Why do only websockets reconnect but HTTP connection do not? This seems to be inconsistent.


(Regarding the bug(s) when connecting to misbehaving ports, I will open another ticket soon ...)

**Comment by rattenburg** [comment]
(sorry, I hit the wrong button)

**Comment by grahambrown11** [comment]
call `NettyHttpClient. setAutoReconnect(false)` before `ari.events().eventWebsocket(...)`
